#! python3
# csv_2_xlsx_converter.py -- Converts the csv files generated by the ImageJ - Fiji macro "Reanálisis_Fura2_Nikon_FINAL_V_2" to xlsx files.
# Moreover, formats the new xlsx file to a elegible file to be analyzed by Calcium_Imaging_Analyzer.py.


import os
import openpyxl
import pandas as pd
from pathlib import Path
import pyinputplus as pyip
import time

from caiman_functions.caiman_styles import caiman_excel_styles as ca_ex_st


def imageJ_reanalysis_multiple_files(folder_path):
    route = Path(folder_path)
    os.chdir(route)
    for folder, _, files in os.walk(route):
        for file in files:
            if ".csv" in file:
                file_route = os.path.join(folder, file)
                read_file = pd.read_csv(file_route)
                splitted_file = file.split(".csv")[0]
                non_space_filename = splitted_file.replace(" ", "_")
                xlsx_append = f"{non_space_filename}.xlsx"
                save_route = os.path.join(folder, xlsx_append)
                read_file.to_excel(save_route, index=None, header=True)

    for folder, _, files in os.walk(route):
        for file in files:
            if "imageJ.xlsx" in file:
                wb = openpyxl.load_workbook(file)
                sheet = wb.active
                sheet.title = "Time Measurement Report"
                sheet.insert_rows(2)
                sheet.insert_rows(1)
                time_header = sheet.cell(row=2, column=1).coordinate
                sheet[time_header] = "Time (s)"
                file_max_column = sheet.max_column
                number_cell = 1
                for column in range(1, file_max_column + 1):
                    try:
                        if "Mean" in sheet.cell(row=2, column=column).value:
                            sample_number_header = sheet.cell(
                                row=2, column=column).coordinate
                            sheet[sample_number_header] = f"#{number_cell} (Ratio)"
                            ca_ex_st.cell_border_style(
                                sample_number_header, sheet)
                            number_cell += 1
                    except TypeError:
                        pass

                splitted_file = file.split(".xlsx")[0]
                wb.save(os.path.join(folder, file))
                print(
                    f"'{splitted_file}.csv' has been converted to '{file}'.")


def imageJ_reanalysis_single_file(route):
    file_path = Path(route)
    read_file = pd.read_csv(file_path)
    splitted_file = file_path.stem
    non_space_filename = splitted_file.replace(" ", "_")
    xlsx_append = f"{non_space_filename}.xlsx"
    save_route = os.path.join(file_path.parent, xlsx_append)
    read_file.to_excel(save_route, index=None, header=True)

    wb = openpyxl.load_workbook(save_route)
    sheet = wb.active
    sheet.title = "Time Measurement Report"
    sheet.insert_rows(2)
    sheet.insert_rows(1)
    time_header = sheet.cell(row=2, column=1).coordinate
    sheet[time_header] = "Time (s)"
    file_max_column = sheet.max_column
    number_cell = 1
    for column in range(1, file_max_column + 1):
        try:
            if "Mean" in sheet.cell(row=2, column=column).value:
                sample_number_header = sheet.cell(
                    row=2, column=column).coordinate
                sheet[sample_number_header] = f"#{number_cell} (Ratio)"
                ca_ex_st.cell_border_style(sample_number_header, sheet)
                number_cell += 1
        except TypeError:
            pass

    splitted_file = save_route.split(".xlsx")[0]
    wb.save(save_route)
    print(f"'{file_path.name}' has been converted to '{xlsx_append}'.")
